### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by RDIL** [cakebotpro/cakebot#36]
Todo:
* [ ] cookie give tests
* [ ] cookie balance tests
* [ ] cookie set tests

**Comment by paramt** [comment]
> - +cookie set
>   - Admin only (done)
>   - Set user cookie count

Does that mean that a Discord server admin can set the cookie counts of that server's members? That would be broken because the cookie counts are synced across servers...

Or do you mean admin as in you?

**Comment by RDIL** [comment]
No I mean me
