### ISSUE TITLE
Global Chat Integration

### ISSUE THREAD

**Issue by RDIL** [cakebotpro/cakebot#77]
Status:
* [x] setup DB
* [x] wait for #76 to get merged
* [ ] translate from cog
  * or write compatibility library
* [ ] link message IDs up to database 
* [ ] don't ruin working production build in doing all this

**Comment by RDIL** [comment]
Closing this until I have more time.

**Comment by Minion3665** [comment]
@RDIL Alright, don't feel pressured to do anything as global chat is (mostly) dead anyway, and looking back at the code my past self wrote it's not hard to see a few serious issues. 

It would likely be more economical to rewrite global chat than to use the code as it is in its current form

Thanks for working with me,
Minion3665
