### ISSUE TITLE
Item trading

### ISSUE THREAD

**Issue by truffleBUTTERvg** [cakebotpro/cakebot#90]
When trying to trade items, cakebot says that item isn't owned by character. Equip/unequip work just fine. There's a party of 8 and we love this game.

**Comment by RDIL** [comment]
Which specific feature are you talking about?

**Comment by truffleBUTTERvg** [comment]
/shop gift <item>
/Shop trade <item>
Both say *hero* does not own <item>

Also...
 /adventure
Says there is already an adventure on this server

**Comment by RDIL** [comment]
Yeah, I think you have the wrong cakebot, we don’t have those features sadly.
